project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!docs/**"


website:
  title: "Psychology Technicians â€“ Wrexham University"
  favicon: images/wrexham-icon.jpeg

  navbar:
    logo: images/wrexham-icon.jpeg
    background: primary
    left:
      - text: "Home"
        href: index.qmd

      - text: "About"
        href: about/index.qmd

      - text: "Equipment"
        href: equipment/index.qmd

      - text: "Students"
        menu:
          - text: "Main Student Page"
            href: students/index.qmd
          - text: "Case Studies"
            href: students/case-studies/index.qmd
          - text: "SONA (In Development)"
            href: students/sona/index.qmd
          - text: "General Ethics Guide"
            href: students/ethics/index.qmd
          - text: "Online Ethics Application Guide"
            href: students/vidatum-academic/index.qmd

      - text: "Resources"
        menu:
          - text: "Main Resources Page"
            href: resources/index.qmd
          - text: "Psychometric Scales"
            href: resources/index2.qmd
          - text: "Experimental Tasks"
            href: resources/index3.qmd
          - text: "Coding Repository"
            href: resources/index4.qmd

      - text: "Recruitment"
        menu:
          - text: "Main Recruitment Page"
            href: recruitment/index.qmd
          - text: "Available Studies"
            href: recruitment/index-2-soon.qmd
          - text: "Researcher Requirements"
            href: recruitment/index-3.qmd


      - text: "OSF"
        menu:
          - text: "GitHub"
            href: https://github.com/WU-Psychology-Technician
          - text: "Gorilla.sc Open"
            href: https://app.gorilla.sc/openmaterials/1112705
          - text: "Research Methods"
            href: rm/index.qmd

      - text: "Contact"
        href: contact/index.qmd

      - text: "News"
        menu:
          - text: "Main News Page"
            href: updates/index.qmd
          - text: "Current Technician Tasks"
            href: updates/tasks.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true

    page-footer:
      right: "Last updated: {{< meta date-modified >}}"

    include-after-body:
      - "_includes/chat-widget-2.html"
      - "_includes/scroll-to-top.html"
      - "_includes/footer.html"
      - "_includes/technician-chat.html"
      - "_includes/background-lines.html"
